### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by moh1122** [RonaldoMoon/Hatch#1]
Hello
while im building the project after i did carthage update xcode building error : module file was created by an older version of the compiler?
any clue ?
i would like to build your project and check it
Thank you

**Comment by Cal-um** [comment]
I had the same issue. I believe it is a problem with iOS charts that will be fixed in a later update - https://github.com/danielgindi/ios-charts/issues/877

I fixed it but I'm not entirely sure how. I used a few different build commands, cleaned from the product menu and after I changed to Generic device it built again successfully. Sorry I couldn't be of more help.

**Comment by Cal-um** [comment]
Ah yeah, the `carthage update --no-use-binaries --platform iOS` is what I used from the command line as well as above.
